name: Run Tests

on:
  push:
    branches:
      - master  # Change this to your default branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use the latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to use the latest version
      with:
        python-version: '3.12'  # Specify the version of Python you want to use

    - name: Cache Python packages
      uses: actions/cache@v3  # Updated to use the latest version
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if your requirements file is in a different location

    - name: Run tests
      run: |
        pytest  # Adjust this command if you're using a different test framework